name: Python deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.7.4]
    steps:
      - run: python -m pip install --upgrade pip
      - run:  pip install .
    - name: test_deploy
      env: |
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        FOLDER: /
