name: Python deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: test_deploy
      run: |
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        FOLDER: /
